Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,12 +8,12 @@ ENV_DIR=$3
 BP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 error() {
-	echo " !     $*" >&2
-	exit 1
+    echo " !     $*" >&2
+    exit 1
 }
 
 topic() {
-	echo "-----> $*"
+    echo "-----> $*"
 }
 
 install_system_deps() {
@@ -50,8 +50,9 @@ libxshmfence-dev
 EOF
     fi
 
-	if [[ "$SUPPORTED_BROWSERS" == *"firefox"* ]]; then
-		cat << EOF >>$build_tmpdir/Aptfile
+    if [[ "$SUPPORTED_BROWSERS" == *"firefox"* ]]; then
+        echo "Adding Firefox dependencies to Aptfile..."
+        cat << EOF >>$build_tmpdir/Aptfile
 # Firefox dependencies
 libdbus-glib-1-2
 libxt6
@@ -61,10 +62,11 @@ libx11-xcb1
 libxcursor1
 libxi6
 EOF
-	fi
+    fi
 
-	if [[ "$SUPPORTED_BROWSERS" == *"firefox"* || "$SUPPORTED_BROWSERS" == *"chromium"* ]]; then
-		cat << EOF >>$build_tmpdir/Aptfile
+    if [[ "$SUPPORTED_BROWSERS" == *"firefox"* || "$SUPPORTED_BROWSERS" == *"chromium"* ]]; then
+        echo "Adding common dependencies to Aptfile..."
+        cat << EOF >>$build_tmpdir/Aptfile
 # Needed by Firefox and Chromium
 libgdk-pixbuf2.0-0
 libcairo-gobject2
@@ -76,41 +78,44 @@ libxdamage1
 libxfixes3
 libgtk-3-0
 EOF
-	fi
+    fi
 
-	case "$STACK" in
-	  "heroku-18")
-	    cat << EOF >>$build_tmpdir/Aptfile
+    case "$STACK" in
+      "heroku-18")
+        echo "Adding heroku-18 dependencies to Aptfile..."
+        cat << EOF >>$build_tmpdir/Aptfile
 libvpx5
 EOF
-	    ;;
-	  "heroku-20")
-	    cat << EOF >>$build_tmpdir/Aptfile
+        ;;
+      "heroku-20")
+        echo "Adding heroku-20 dependencies to Aptfile..."
+        cat << EOF >>$build_tmpdir/Aptfile
 libvpx6
 EOF
-	    ;;
-		"heroku-22")
-	    cat << EOF >>$build_tmpdir/Aptfile
+        ;;
+        "heroku-22")
+        echo "Adding heroku-22 dependencies to Aptfile..."
+        cat << EOF >>$build_tmpdir/Aptfile
 libvpx7
 EOF
-	    ;;
-	  *)
-	    error "STACK must be 'heroku-18', 'heroku-20', or 'heroku-22'"
-	esac
+        ;;
+      *)
+        error "STACK must be 'heroku-18', 'heroku-20', or 'heroku-22'"
+    esac
 
-	local cache_tmpdir=$(mktemp -d)
+    local cache_tmpdir=$(mktemp -d)
 
-	HOME=/app $buildpack_tmpdir/bin/compile $build_tmpdir $cache_tmpdir
-	if [ $? -ne 0 ]; then
-		rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
-		error "Could not install dependencies"
-	fi
-	mv $build_tmpdir/.apt $BUILD_DIR
-	# mv file in case user is using .profile.d
-	mkdir -p $BUILD_DIR/.profile.d/
-	mv $build_tmpdir/.profile.d/000_apt.sh $BUILD_DIR/.profile.d/
+    HOME=/app $buildpack_tmpdir/bin/compile $build_tmpdir $cache_tmpdir
+    if [ $? -ne 0 ]; then
+        rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
+        error "Could not install dependencies"
+    fi
+    mv $build_tmpdir/.apt $BUILD_DIR
+    # mv file in case user is using .profile.d
+    mkdir -p $BUILD_DIR/.profile.d/
+    mv $build_tmpdir/.profile.d/000_apt.sh $BUILD_DIR/.profile.d/
 
-	rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
+    rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
 }
 
 configure_export_env() {
@@ -118,27 +123,27 @@ configure_export_env() {
     mkdir -p $BUILD_DIR/.profile.d
     cat << EOF >$BUILD_DIR/.profile.d/001_playwright.sh
 export PLAYWRIGHT_BROWSERS_PATH=0
-# They are not referenced correctly for ffmpeg
-export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/:/app/.apt/lib/x86_64-linux-gnu/
+export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/lib/x86_64-linux-gnu:/app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/
 EOF
 
     # Give environment variable to other buildpacks
     echo "export PLAYWRIGHT_BROWSERS_PATH=0" >> "$BP_DIR/export"
     export PLAYWRIGHT_BROWSERS_PATH=0
+    echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/lib/x86_64-linux-gnu:/app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/" >> "$BP_DIR/export"
+    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/lib/x86_64-linux-gnu:/app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/
 }
 
-# See here as a reference: https://devcenter.heroku.com/articles/buildpack-api#bin-compile
 export_env_dir() {
-  env_dir=$1
-  acceptlist_regex=${2:-''}
-  denylist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
-  if [ -d "$env_dir" ]; then
-    for e in $(ls $env_dir); do
-      echo "$e" | grep -E "$acceptlist_regex" | grep -qvE "$denylist_regex" &&
-      export "$e=$(cat $env_dir/$e)"
-      :
-    done
-  fi
+    env_dir=$1
+    acceptlist_regex=${2:-''}
+    denylist_regex=${3:-'^(PATH|GIT_DIR|CPATH|CPPATH|LD_PRELOAD|LIBRARY_PATH)$'}
+    if [ -d "$env_dir" ]; then
+        for e in $(ls $env_dir); do
+            echo "$e" | grep -E "$acceptlist_regex" | grep -qvE "$denylist_regex" &&
+            export "$e=$(cat $env_dir/$e)"
+            :
+        done
+    fi
 }
 
 install_chromium() {
@@ -159,3 +164,7 @@ export_env_dir "$ENV_DIR" PLAYWRIGHT_BUILDPACK_BROWSERS
 install_system_deps
 configure_export_env
 install_chromium
+
+echo "Verifying installed libraries..."
+echo $LD_LIBRARY_PATH
+ls -l /app/.apt/usr/lib/x86_64-linux-gnu | grep libatk-bridge
