Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,29 +8,29 @@ ENV_DIR=$3
 BP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 error() {
-	echo " !     $*" >&2
-	exit 1
+    echo " !     $*" >&2
+    exit 1
 }
 
 topic() {
-	echo "-----> $*"
+    echo "-----> $*"
 }
 
 install_system_deps() {
-	topic "Installing System Dependencies"
+    topic "Installing System Dependencies"
 
-	APT_BUILDPACK="https://github.com/heroku/heroku-buildpack-apt"
-	local buildpack_tmpdir=$(mktemp -d)
-	cd $buildpack_tmpdir && git clone $APT_BUILDPACK .
+    APT_BUILDPACK="https://github.com/heroku/heroku-buildpack-apt"
+    local buildpack_tmpdir=$(mktemp -d)
+    cd $buildpack_tmpdir && git clone $APT_BUILDPACK .
 
-	local build_tmpdir=$(mktemp -d)
-	mkdir -p $build_tmpdir
+    local build_tmpdir=$(mktemp -d)
+    mkdir -p $build_tmpdir
 
-	SUPPORTED_BROWSERS=${PLAYWRIGHT_BUILDPACK_BROWSERS:-chromium,firefox,webkit}
-	echo "Installing Playwright dependencies (env: PLAYWRIGHT_BUILDPACK_BROWSERS) for $SUPPORTED_BROWSERS."
+    SUPPORTED_BROWSERS=${PLAYWRIGHT_BUILDPACK_BROWSERS:-chromium,firefox,webkit}
+    echo "Installing Playwright dependencies (env: PLAYWRIGHT_BUILDPACK_BROWSERS) for $SUPPORTED_BROWSERS."
 
-	if [[ "$SUPPORTED_BROWSERS" == *"chromium"* ]]; then
-		cat << EOF >>$build_tmpdir/Aptfile
+    if [[ "$SUPPORTED_BROWSERS" == *"chromium"* ]]; then
+        cat << EOF >>$build_tmpdir/Aptfile
 # Chromium dependencies
 libnspr4
 libnss3
@@ -44,10 +44,10 @@ libxrandr2
 libatspi2.0-0
 libxshmfence-dev
 EOF
-	fi
+    fi
 
-	if [[ "$SUPPORTED_BROWSERS" == *"firefox"* ]]; then
-		cat << EOF >>$build_tmpdir/Aptfile
+    if [[ "$SUPPORTED_BROWSERS" == *"firefox"* ]]; then
+        cat << EOF >>$build_tmpdir/Aptfile
 # Firefox dependencies
 libdbus-glib-1-2
 libxt6
@@ -57,10 +57,10 @@ libx11-xcb1
 libxcursor1
 libxi6
 EOF
-	fi
+    fi
 
-	if [[ "$SUPPORTED_BROWSERS" == *"firefox"* || "$SUPPORTED_BROWSERS" == *"chromium"* ]]; then
-		cat << EOF >>$build_tmpdir/Aptfile
+    if [[ "$SUPPORTED_BROWSERS" == *"firefox"* || "$SUPPORTED_BROWSERS" == *"chromium"* ]]; then
+        cat << EOF >>$build_tmpdir/Aptfile
 # Needed by Firefox and Chromium
 libgdk-pixbuf2.0-0
 libcairo-gobject2
@@ -74,10 +74,10 @@ libgtk-3-0
 libdrm2
 libxrandr2
 EOF
-	fi
+    fi
 
-	# Adding missing dependencies mentioned in the error message
-	cat << EOF >>$build_tmpdir/Aptfile
+    # Adding missing dependencies mentioned in the error message
+    cat << EOF >>$build_tmpdir/Aptfile
 # Additional dependencies
 libatk1.0-0
 libatk-bridge2.0-0
@@ -92,39 +92,39 @@ libxkbcommon0
 libasound2
 EOF
 
-	case "$STACK" in
-	  "heroku-18")
-	    cat << EOF >>$build_tmpdir/Aptfile
+    case "$STACK" in
+      "heroku-18")
+        cat << EOF >>$build_tmpdir/Aptfile
 libvpx5
 EOF
-	    ;;
-	  "heroku-20")
-	    cat << EOF >>$build_tmpdir/Aptfile
+        ;;
+      "heroku-20")
+        cat << EOF >>$build_tmpdir/Aptfile
 libvpx6
 EOF
-	    ;;
-		"heroku-22")
-	    cat << EOF >>$build_tmpdir/Aptfile
+        ;;
+        "heroku-22")
+        cat << EOF >>$build_tmpdir/Aptfile
 libvpx7
 EOF
-	    ;;
-	  *)
-	    error "STACK must be 'heroku-18', 'heroku-20', or 'heroku-22'"
-	esac
+        ;;
+      *)
+        error "STACK must be 'heroku-18', 'heroku-20', or 'heroku-22'"
+    esac
 
-	local cache_tmpdir=$(mktemp -d)
+    local cache_tmpdir=$(mktemp -d)
 
-	HOME=/app $buildpack_tmpdir/bin/compile $build_tmpdir $cache_tmpdir
-	if [ $? -ne 0 ]; then
-		rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
-		error "Could not install dependencies"
-	fi
-	mv $build_tmpdir/.apt $BUILD_DIR
-	# mv file in case user is using .profile.d
-	mkdir -p $BUILD_DIR/.profile.d/
-	mv $build_tmpdir/.profile.d/000_apt.sh $BUILD_DIR/.profile.d/
+    HOME=/app $buildpack_tmpdir/bin/compile $build_tmpdir $cache_tmpdir
+    if [ $? -ne 0 ]; then
+        rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
+        error "Could not install dependencies"
+    fi
+    mv $build_tmpdir/.apt $BUILD_DIR
+    # mv file in case user is using .profile.d
+    mkdir -p $BUILD_DIR/.profile.d/
+    mv $build_tmpdir/.profile.d/000_apt.sh $BUILD_DIR/.profile.d/
 
-	rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
+    rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
 }
 
 configure_export_env() {
